---
title: "COPCOV_plots"
author: "James Watson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = T, cache.comments = FALSE,
                      echo = F, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)
library(survival)
library(survminer)
library(lubridate)
library(tidyverse)
library(epitools)
```

## R Markdown

```{r}
# surv_dat_old = readxl::read_excel('Data/Time_events_old.xlsx')
surv_dat = readxl::read_excel('Data/Time_events_16_01_2023_REVISED_MM_WS_Latest_FINAL_19_01_23.xlsx')
# surv_dat = surv_dat %>% filter(!duplicated(subjectno))

table(surv_dat$All_ill_event, surv_dat$treatment)
table(surv_dat$pcr_event, surv_dat$treatment)

surv_dat = surv_dat %>% group_by(subjectno) %>%
  mutate(swab_date = sort(c(c_date,sample_date))[1]) %>%
  distinct(subjectno, .keep_all = T) %>%
  mutate(
    EOS = as.numeric(difftime(as.POSIXct(fs_date), as.POSIXct(random_date),units = 'days')),
    Swab_time = ifelse(All_ill_event==1, 
                       as.numeric(difftime(as.POSIXct(swab_date),
                                           as.POSIXct(random_date),
                                           units = 'days')),
                       NA),
    PCR_time_event = ifelse(pcr_event==1, Swab_time, EOS),
    All_ill_time_event = ifelse(All_ill_event==1, Swab_time, EOS)
  ) %>% ungroup %>%
  arrange(All_ill_event, pcr_event)

View(surv_dat[surv_dat$All_ill_event==1,
              c('random_date','swab_date','EOS',
                'pcr_event','All_ill_event',
                'PCRFu_days','All_cFu_days',
                'PCR_time_event','All_ill_time_event')])

survmod = survfit(Surv(PCRFu_days, pcr_event) ~ treatment,
                  data = surv_dat)
LRTest=survdiff(Surv(PCRFu_days, pcr_event) ~ treatment,
                data = surv_dat)
pchisq(LRTest$chisq, length(LRTest$n)-1, lower.tail = FALSE)

survmod_all = survfit(Surv(All_cFu_days, All_ill_event) ~ treatment,
                      data = surv_dat)
LRTest=survdiff(Surv(All_cFu_days, All_ill_event) ~ treatment,
                data = surv_dat)
pchisq(LRTest$chisq, length(LRTest$n)-1, lower.tail = FALSE)
```



```{r Figure2, fig.width=12}
splots <- list()

splots[[1]] <- 
  ggsurvplot(survmod_all, conf.int = T,#data = surv_dat,
             xlim=c(0,90), ylim=c(0, .05), 
             xlab='Days in study',
             pval = T,
             pval.coord = c(10,.03),
             break.x.by=30,
             palette = 'Set2',fun = function(x) 1-x,
             legend.labs = c('Chloroquine/hydroxychloroquine',
                             'Placebo'),
             risk.table.y.text.col	= T,
             risk.table = T,risk.table.y.text=F,
             legend.title='',
             font.x=15,font.y=15,font.table=15,
             font.legend=15,
             ylab='All-cause PCR-confirmed respiratory illness', 
             surv.scale='percent', 
             ggtheme = theme_survminer(base_family='serif'))

splots[[2]] <- ggsurvplot(survmod, conf.int = T,data = surv_dat,
                          xlim=c(0,90), ylim=c(0, .05), 
                          xlab='Days in study',
                          pval = T,
                          pval.coord = c(10,.03),
                          break.x.by=30,
                          palette = 'Set2',fun = function(x) 1-x,
                          legend.labs = c('Chloroquine/hydroxychloroquine',
                                          'Placebo'),
                          risk.table.y.text.col	= T,
                          risk.table = T,risk.table.y.text=F,
                          legend.title='',
                          font.x=15,font.y=15,font.table=15,
                          font.legend=15,
                          ylab='PCR-confirmed COVID-19', 
                          surv.scale='percent', 
                          ggtheme = theme_survminer(base_family='serif'))

res=
  arrange_ggsurvplots(splots,
                      print = T)
```

